// alert
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

// profile
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const GET_FOLLOWERS_OF_PROFILE = 'GET_FOLLOWERS_OF_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const GET_FOLLOWS = 'GET_FOLLOWS';
export const FOLLOWS_ERROR = 'FOLLOWS_ERROR';

// search
export const SEARCH_PROFILES = 'SEARCH_PROFILES';
export const SEARCH_MESSAGES = 'SEARCH_MESSAGES';
export const SEARCH_HASHTAGS = 'SEARCH_HASHTAGS';
export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
export const GET_PROFILEOFINTEREST = 'GET_PROFILEOFINTEREST';
export const CLEAR_PROFILEOFINTEREST = 'CLEAR_PROFILEOFINTEREST';
export const SEARCH_ERROR = 'SEARCH_ERROR';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
export const MESSAGE_SEARCH_ERROR = 'MESSAGE_SEARCH_ERROR';
export const PROFILE_SEARCH_ERROR = 'PROFILE_SEARCH_ERROR';

// message
export const GET_OTHER_MESSAGES = 'GET_OTHER_MESSAGES';
export const GET_MY_MESSAGES = 'GET_MY_MESSAGES';
export const GET_MESSAGES_FOLLOWED_PROFILE = 'GET_MESSAGES_FOLLOWED_PROFILE';
export const MESSAGE_ERROR = 'MESSAGE-ERROR';
export const POST_MESSAGE = 'POST_MESSAGE';
