FROM node:latest

WORKDIR /app 

COPY package.json /app
COPY package-lock.json /app

RUN npm install && npm cache clean --force
ENV PATH /app/node_modules/.bin:$PATH

WORKDIR /app/src

COPY . .

EXPOSE 7050

CMD npm start