openapi: 3.0.1
info:
  title: moody Search Service
  description: This is the REST API documentation for the moody search_service
  version: 1.0.0
servers:
  - url: /api
tags:
  - name: search
    description: Searching form profiles

paths:
  /search/profiles:
    get:
      tags:
        - search
      summary: Get profiles from a specific search term
      description: Search for usernames of profiles given a specific search term
      parameters:
        - name: username
          in: query
          required: true
          schema:
            type: string
            example: go
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: number
                    example: 200
                  profiles:
                    type: array
                    items:
                      $ref: '#/components/schemas/Profile'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: number
                    example: 401
                  msg:
                    type: string
                    example: Unauthorized - Token is not valid
        404:
          description: No profiles found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: number
                    example: 404
                  msg:
                    type: string
                    example: No profiles found
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: number
                    example: 500
                  msg:
                    type: string
                    example: Internal Server Error
      security:
        - authentication: []
components:
  schemas:
    Profile:
      required:
        - birthday
        - hometown
        - gender
      type: object
      properties:
        birthday:
          type: string
          format: date
        hometown:
          type: string
          example: Linz
        gender:
          type: string
          example: female
          enum:
            - male
            - female
            - transgender
        privacy:
          type: string
          example: public
          default: public
          enum:
            - private
            - public
        notifications:
          type: boolean
          example: false
          default: false
        username:
          type: string
          example: Hugo
  securitySchemes:
    authentication:
      type: apiKey
      name: Authorization
      in: header
