openapi: 3.0.1
info:
  title: moody Search Service
  description: This is the REST API documentation for the moody search_service
  version: 1.0.0
servers:
  - url: /api

paths:
  /search/profiles:
    get:
      tags:
        - search
      summary: Get profiles from a specific search term
      description: Search for usernames of profiles given a specific search term
      parameters:
        - name: username
          in: query
          required: true
          schema:
            type: string
            example: go
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Profile'
        404:
          description: No profiles found
          content: {}
        500:
          description: Internal server error
          content: {}
      security:
        - authentication: []
components:
  schemas:
    Profile:
      required:
        - birthday
        - hometown
        - gender
      type: object
      properties:
        birthday:
          type: string
          format: date
        hometown:
          type: string
          example: Linz
        gender:
          type: string
          example: female
          enum:
            - male
            - female
            - transgender
        background:
          type: string
          example: none
        privacy:
          type: string
          example: public
          default: public
          enum:
            - private
            - public
        notifications:
          type: boolean
          example: false
          default: false
        username:
          type: string
          example: Hugo
  securitySchemes:
    authentication:
      type: apiKey
      name: Authorization
      in: header
